### ISSUE TITLE
sif2/sifas/stills broken due to idol.st cloudflare

### ISSUE THREAD

**Issue by 42GAMI** [DemonicSavage/mikan#85]
idol.st have implemented cloudflare and as a result sif2/sifas/stills are now broken. 
```
C:\Users\redacted>mikan --sifas
Searching for new or missing items...
Error: An error occured while getting number of pages.

C:\Users\redacted>mikan --sif2
Searching for new or missing items...
Error: An error occured while getting number of pages.

C:\Users\redacted>mikan --stills
Searching for new or missing items...
Error: An error occured while getting number of pages.```

**Comment by DemonicSavage** [comment]
I will try to look for a solution as soon as possible.

**Comment by DemonicSavage** [comment]
It is working today.

Seems like them enabling Cloudflare IUAM was a temporary measure.

As I wasn't able to find a solution that isn't extremely impractical, if they ever enable it permanently, that would mean the end of these particular plugins, unfortunately.
